version: '3'

networks:
  helpdesk:

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: admin
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: helpdesk
    networks: 
      - helpdesk
    ports:
      - "3307:3306"
    volumes:
      - ./src/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - ./src/:/code
    ports:
      - "8020:8000"
    depends_on: 
      - db
    networks:
      - helpdesk