# Generated by Django 2.0 on 2018-08-14 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000, verbose_name='Texto')),
                ('data', models.DateTimeField(default=datetime.datetime(2018, 8, 14, 13, 40, 42, 599420), verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45, verbose_name='Título')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('email', models.CharField(max_length=45, verbose_name='E-mail')),
                ('departamento', models.CharField(max_length=45, verbose_name='Departamento')),
                ('host', models.CharField(max_length=45, verbose_name='Host')),
                ('dataAbertura', models.DateTimeField(default=datetime.datetime(2018, 8, 14, 13, 40, 42, 598328), verbose_name='Data de Abertura')),
                ('status', models.IntegerField(choices=[(0, 'em Aberto'), (1, 'em Andamento'), (2, 'Finalizado')], default=0, verbose_name='Status')),
                ('codigo', models.CharField(default='', max_length=20, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
