# Generated by Django 2.0.5 on 2018-06-04 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20180604_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 20, 33, 38, 613576, tzinfo=utc), verbose_name='Data de Abertura'),
        ),
    ]
