# Generated by Django 2.0 on 2018-07-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20180719_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 51, 58, 120111), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(default='none', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 51, 58, 119628), verbose_name='Data de Abertura'),
        ),
    ]
