# Generated by Django 2.0.5 on 2018-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45, verbose_name='Título')),
                ('descricao', models.CharField(max_length=2000, verbose_name='Descrição')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('email', models.CharField(max_length=45, verbose_name='E-mail')),
                ('departamento', models.CharField(max_length=45, verbose_name='Departamento')),
                ('dataAbertura', models.DateTimeField(verbose_name='Data de Abertura')),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
