# Generated by Django 2.0.5 on 2018-05-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180518_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aberto'), (1, 'Andamento'), (2, 'Finalizado')], verbose_name='Status'),
        ),
    ]
