# Generated by Django 2.0.5 on 2018-05-23 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180518_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscarTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(verbose_name='Código')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 19, 46, 52, 285529, tzinfo=utc), verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aberto'), (1, 'Andamento'), (2, 'Finalizado')], default=0, verbose_name='Status'),
        ),
    ]
