# Generated by Django 2.0.5 on 2018-06-04 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180523_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuscarTicket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(default=1, max_length=20, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 17, 29, 37, 674649), verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'em Aberto'), (1, 'em Andamento'), (2, 'Finalizado')], default=0, verbose_name='Status'),
        ),
    ]
