# Generated by Django 2.0.5 on 2018-06-04 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20180604_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 20, 30, 39, 683743, tzinfo=utc), verbose_name='Data de Abertura'),
        ),
    ]
