# Generated by Django 2.0.5 on 2018-06-05 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180604_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 14, 6, 46, 887509), verbose_name='Data de Abertura'),
        ),
    ]
