# Generated by Django 2.0 on 2018-07-19 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20180606_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 31, 16, 178721), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 31, 16, 178000), verbose_name='Data de Abertura'),
        ),
    ]
