# Generated by Django 2.0 on 2018-07-19 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20180719_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 45, 14, 809866), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 45, 14, 809377), verbose_name='Data de Abertura'),
        ),
    ]
