# Generated by Django 2.0 on 2018-07-19 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20180719_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 58, 45, 839577), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(default='', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 12, 58, 45, 839091), verbose_name='Data de Abertura'),
        ),
    ]
