# Generated by Django 2.0 on 2018-07-19 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20180719_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 16, 10, 49, 309033, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 16, 10, 49, 308518, tzinfo=utc), verbose_name='Data de Abertura'),
        ),
    ]
