# Generated by Django 2.0 on 2018-08-09 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20180719_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='host',
            field=models.CharField(default='', max_length=45, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 15, 53, 11, 586889), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAbertura',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 15, 53, 11, 586407), verbose_name='Data de Abertura'),
        ),
    ]
